[project]
name = "qaboard-site-sirc"
version = "1.0.0"
description = "QABoard site defaults for Samsung SIRC"
requires-python = ">=3.7"
dependencies = [
    "cde @ git+ssh://git@gitlab-srv/cde/cde-python",
]

[project.entry-points."qaboard.site"]
sirc = "qaboard_site_sirc:defaults"

[project.entry-points."qaboard.hooks"]
fix_permissions = "qaboard_site_sirc.hooks:fix_permissions"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
