image: gitlab-srv.transchip.com:4567/dvs/slamvizapp

variables:
  DOCKER_IMAGE: gitlab-srv.transchip.com:4567/dvs/slamresultsvizapp
    
before_script:
  # Our CI needs to access the LSF cluster. We do it via SSH
  - export SSH_LSF="ssh -o StrictHostKeyChecking=no arthurf@planet31"
  # manually managed build cache on LSF
  - export SAMSUNG_CI_ROOT_DIR="/home/arthurf/ci/$CI_PROJECT_PATH"
  - export SAMSUNG_CI_BRANCH_DIR="$SAMSUNG_CI_ROOT_DIR/branches/$CI_COMMIT_REF_SLUG"
  # clone/fetch and checkout the commit on LSF
  - >
    function update_lsf() {
      $SSH_LSF "mkdir -p $SAMSUNG_CI_BRANCH_DIR"
      export TRY_CLONE="git clone --depth=10 -b $CI_COMMIT_REF_NAME git@gitlab-srv:dvs/slamvizapp.git"
      export TRY_PULL="cd slamvizapp && git fetch origin --depth=10 $CI_COMMIT_REF_NAME && git reset --hard HEAD"
      cmd="cd $SAMSUNG_CI_BRANCH_DIR; $TRY_CLONE || $TRY_PULL; git checkout $CI_COMMIT_SHA"
      echo '> ' $cmd;
      eval $cmd;
    }

stages:
  - build
  - test
  - deploy

# only tests that the syntax is OK
test-backend:
  stage: test
  script:
    - pip install .

test-frontend:
  stage: test
  script:
    - cd slamvizapp-webapp
    - echo "skipped" # yarn install
    - echo "skipped" # yarn build
# we could run more tests with: 
#    - CI=true yarn test

deploy_staging:
  stage: deploy
  script:
    - update_lsf
    - ssh gpu09-dt "cd $SAMSUNG_CI_BRANCH_DIR/slamvizapp; docker build -t $DOCKER_IMAGE:$CI_ENVIRONMENT_SLUG . && docker push $DOCKER_IMAGE:$CI_ENVIRONMENT_SLUG"
    - ssh planet31 docker pull $DOCKER_IMAGE:$CI_ENVIRONMENT_SLUG
    - ssh planet31 "docker stop slamvizapp-$CI_ENVIRONMENT_SLUG || true"
    - ssh planet31 "docker rm slamvizapp-$CI_ENVIRONMENT_SLUG || true"
    - ssh planet31 "zsh --login -c \"CI_ENVIRONMENT_SLUG=\"$CI_ENVIRONMENT_SLUG\" ./dvs/slamvizapp/deployment/start-docker.sh\""
  environment:
    name: staging
    url: http://dvs:6000
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - update_lsf
    - ssh gpu09-dt "cd $SAMSUNG_CI_BRANCH_DIR/slamvizapp; docker build -t $DOCKER_IMAGE:$CI_ENVIRONMENT_SLUG . && docker push $DOCKER_IMAGE:$CI_ENVIRONMENT_SLUG"
    - ssh planet31 docker pull $DOCKER_IMAGE:$CI_ENVIRONMENT_SLUG
    - ssh planet31 "docker stop slamvizapp-$CI_ENVIRONMENT_SLUG || true"
    - ssh planet31 "docker rm slamvizapp-$CI_ENVIRONMENT_SLUG || true"
    - ssh planet31 "zsh --login -c \"CI_ENVIRONMENT_SLUG=\"$CI_ENVIRONMENT_SLUG\" ./dvs/slamvizapp/deployment/start-docker.sh\""
  environment:
    name: production
    url: http://dvs:5000
  only:
    - master
  when: manual
