version: "3.5"

services:
  # don't show logs from those services
  pgadmin:
    logging:
      driver: none
  db:
    logging:
      driver: none
  redis:
    logging:
      driver: none
  cantaloupe:
    logging:
      driver: none
  proxy:
    ports:
    - 5001:5001

  backend:
    volumes:
    - ./qaboard:/qaboard/qaboard
    - ./backend:/qaboard/backend
    - ${HOME}:${HOME}
    - ./pyproject.toml:/qaboard/pyproject.toml
    environment:
    - FLASK_APP=backend
    - FLASK_ENV=development
    - FLASK_DEBUG=1
    # in dev we run as the user so we can't use the system python owned by root
    - UV_PROJECT_ENVIRONMENT=
    - PYTHONNOUSERSITE=1
    # - QABOARD_DB_ECHO=true
    - UWSGI_STATS=true
    - QABOARD_DATA_DIR=/qaboard/backend/data
    # Connect to the production database
    - QABOARD_DB_HOST=qa
    - SSH_AUTH_SOCK=/ssh-agent
    working_dir: /qaboard/backend
    # With what's just below, everything works except being able to delete files owned by other users
    # We wish we could do this, then remove sudo from the dockerfile, and use this command...
    # command: flask run --host 0.0.0.0 --with-threads --port 5152
    # user: "11611:10"
    # cap_add:
    #   - SETUID
    #   - SETGID
    # But non-root users don't gain capabilities...
    # uv add lxml xmlsec uwsgi --no-binary-package uwsgi --no-binary-package lxml --no-binary-package xmlsec --refresh-package lxml --refresh-package xmlsec --refresh-package uwsgi --no-cache --reinstall
    # flask run --with-threads --host 0.0.0.0 --port 5152
    command: >
      bash -c "
      echo '${USER} ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        su ${USER} -c 'uv run flask run --host 0.0.0.0 --with-threads --port 5152'
      "
    ports:
    - "${QABOARD_DEV_BACKEND_PORT:-5152}:5152"
    # logging:
    #   driver: json-file

  frontend:
    build:
      target: dev
    volumes:
    - ./webapp:/app
    working_dir: /app
    environment:
    - HOME=/app
    - NPM_CONFIG_USERCONFIG=/app
    # Should we comment it out by default?
    - HOST=0.0.0.0
    - DANGEROUSLY_DISABLE_HOST_CHECK=true
    - CHOKIDAR_USEPOLLING=true
    # - REACT_EDITOR=code
    # Relay API requests to your development server
    - REACT_APP_QABOARD_API_HOST=http://backend:5152
    - REACT_APP_QABOARD_HOST=http://proxy:5151
    ### At SIRC ####
    - HTTP_PROXY=
    - http_proxy=
    - REACT_APP_QABOARD_HOST=http://proxy
    user: "11611:10"
    ports:
    - "${QABOARD_DEV_FRONTEND_PORT:-3000}:3000"
    depends_on:
    - proxy
    - backend
    logging:
      driver: json-file
  
  website:
    command: yarn start
    volumes:
    - ./website:/website
    environment:
      # to access the server from outside the docker environment
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      # with SIRC's filesystem that doesn't send update events
      - CHOKIDAR_USEPOLLING=true
      # at SIRC to deal with broken proxies/certs
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - 6051:3000
