# https://docs.docker.com/compose/
# https://docs.docker.com/compose/compose-file
version: "3.5"

# Production:
#   # https://docs.docker.com/compose/production/
#   # adds to all services "restart: always"
#   docker compose -f docker-compose.yml -f production.yml up -d
# Development:
#   # Mounts the local code for easy debugging with reloading
#   docker compose -f docker-compose.yml -f development.yml up
# Site-specific overlay:
#   docker compose -f docker-compose.yml -f production.yml -f deployments/mysite.yml up -d

# Container names will be prefixed with "qaboard-"

# Usage:
# - The application is served on port 5151 by default
# - Your responsibility to setup another reverse proxy on top for SSL

# General docker compose usage:
#   docker compose up                    # start the whole stack
#   docker compose up -d                 # ...as a daemon
#   docker compose stop                  # stop the stack's containers
#   docker compose down --volumes        # [dangerous] remove the data too
#   docker compose build web             # build a single service
#   docker compose logs -f web           # logs! -t/--timestamps --tail=10
#   docker compose run web env           # "docker-run" commands from a service
#   docker compose up --no-deps -d web   # start a single service


volumes:
  data: {}              # git clones (and custom batches.yaml for now...)
  db: {}
  redis_data: {}
  rabbitmq-data: {}
  cache_cantaloupe: {}  # cache for the iiif image server
  pgadmin: {}
  # all builds still available for smooth upgrades
  frontend_builds: {}
  website_builds: {}

services:
  # For all configuration options:
  # https://hub.docker.com/_/postgres
  # https://stackoverflow.com/questions/30848670/how-to-customize-the-configuration-file-of-the-official-postgresql-docker-image
  db:
    image: postgres:12-alpine
    expose:
    - "5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./services/db:/opt
    environment:
      - POSTGRES_USER=qaboard
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qaboard

  backend:
    image: "arthurflam/qaboard:backend"
    build:
      context: .
      dockerfile: backend/Dockerfile
    # Wait for the database to be ready - https://docs.docker.com/compose/startup-order/
    command: ["./wait-for-it.sh", "${QABOARD_DB_HOST-db}:${QABOARD_DB_PORT-5432}", "--", "/qaboard/backend/init.sh"]
    depends_on:
      - db
      - redis
    expose:
    - "3000"
    volumes:
    - data:/var/qaboard
    environment:
    - SECRET_KEY
    - UWSGI_PROCESSES=2
    - UWSGI_LISTEN_QUEUE_SIZE=100
    - QABOARD_DB_HOST
    - QABOARD_DB_PORT
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - GITLAB_ACCESS_TOKEN
    - QABOARD_LOGIN_TYPE=${QABOARD_LOGIN_TYPE:-LOCAL} # LOCAL/LDAP/SAML
    - QABOARD_LOGIN_RESTRICTED=${QABOARD_LOGIN_RESTRICTED:-} # true/false
    - QABOARD_LOGIN_RESTRICTED_YAML=${QABOARD_LOGIN_RESTRICTED_YAML:-} # path
    - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:${QABOARD_PORT_RABBITMQ:-5672}//

  frontend:
    image: "arthurflam/qaboard:frontend"
    build:
      context: webapp
      shm_size: 6gb
    volumes:
    - frontend_builds:/builds
    # by default we assume you run the QA-Board on localhost, but will want to change this
    environment:
    - REACT_APP_QABOARD_HOST=http://localhost:5151


  # Message broker used by the celery task scheduler
  # https://hub.docker.com/_/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    # To store the data at a non-random location
    hostname: rabbitmq-qaboard
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    ports:
    - ${QABOARD_PORT_RABBITMQ:-5672}:5672
    - ${QABOARD_PORT_RABBITMQ_MNGT:-15672}:15672


  # https://flower.readthedocs.io/en/latest/config.html#options
  flower:
    build:
      context: .
      dockerfile: services/flower.Dockerfile
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_BROKER_API=http://guest:guest@rabbitmq:15672/api/
      - FLOWER_PORT=8888
      - FLOWER_URL_PREFIX=flower
    command: celery -A qaboard.runners.celery_app flower
    ports:
      - "8888:8888"
    depends_on:
        - rabbitmq

  website:
    image: "arthurflam/qaboard:website"
    build:
      context: website
      shm_size: 4gb
      # by default we assume you run the QA-Board on localhost, but will want to change this
      args:
        - QABOARD_URL=${QABOARD_URL:-http://localhost:5151}
    volumes:
    - website_builds:/builds


  # nginx as reverse-proxy
  # https://hub.docker.com/_/nginx
  proxy:
    image: docker.pkg.github.com/samsung/qaboard/proxy
    build:
      context: services/nginx
    # # https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration
    command: >-
      /bin/bash -c "
        set -e;
        rm -rf /etc/nginx;
        cp -r /tmp/etc/nginx /etc;
        if [ -d /tmp/deployment/nginx/conf.d/ ]; then
          cp -r /tmp/deployment/nginx/conf.d/* /etc/nginx/conf.d/;
        fi;
        envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf;
        exec $${NGINX_BIN:-nginx} -g 'daemon off;'
      "
    environment:
    - NGINX_USER=nginx
    ports:
    - ${QABOARD_PORT_HTTP:-5151}:80
    volumes:
    - ./services/nginx:/tmp/etc/nginx
    - frontend_builds:/builds:ro
    - website_builds:/docs:ro
    depends_on:
    - backend
    - cantaloupe
    - flower

  # IIIF image server to serve images as tiles
  cantaloupe:
    image: "arthurflam/qaboard:cantaloupe"
    build:
      context: ./services/cantaloupe
    expose:
    - "8182"
    volumes:
    - cache_cantaloupe:/var/cache/cantaloupe
    - /srv/cantaloupe
    # INSECURE/FIXME: obviously it's not a great default, but not clear how to do better
    - /:/repository
    environment:
      CANTALOUPE_MEM_START: 1g
      CANTALOUPE_MEM_MAX: 2g
    command: sh -c 'java -Dcantaloupe.config=/etc/cantaloupe.properties -Dcom.sun.media.jai.disableMediaLib=true -Xms$${CANTALOUPE_MEM_START} -Xmx$${CANTALOUPE_MEM_MAX} -jar /usr/local/cantaloupe/cantaloupe-$${VERSION}.jar'


  # For convenience, we also bundle pgadmin
  # Login at localhost:5050, and use "password" as password
  # Note: pgadmin ships with utilities at e.g. /usr/local/pgsql-12
  # More configuration options, e.g. reverse proxying with nginx:
  # https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@domain.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-SuperSecret}
      # if you want to host it under a subdirectory, add a location.proxy_pass to the nginx conf
      # SCRIPT_NAME: /pgadmin
    volumes:
      - pgadmin:/root/.pgadmin
      # https://www.pgadmin.org/docs/pgadmin4/development/import_export_servers.html
      - ./services/pgadmin/servers.json:/pgadmin4/servers.json
      - ./services/pgadmin/passfile:/pgadmin4/passfile
    ports:
    - "${PGADMIN_PORT:-5050}:80"


  redis:
    image: redis:7
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
