services:
  fluentd:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:fluentd"
    build:
      context: services/fluentd
      dockerfile: fluentd.Dockerfile
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./services/fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
    environment:
      - ELASTIC_HOST=jenkins-test.transchip.com
      - FLUENTD_CONF=fluentd.conf