version: "3.5"
# dns: 127.0.0.53
# dns_search: transchip.com

services:
  iiif-cde:
    image: "gitlab-srv:4567/dvs/slamvizapp/iipsrv-cde"
    # command: 'tail -f /dev/null' # keeps the container up for debugging, but does nothing...
    restart: always
    expose:
    - "80"
    volumes:
    - /opt/dockermounts/stage/algo_data:/var/www/localhost/images/stage/algo_data
    - /algo/CIS/outputs:/var/www/localhost/images/algo/CIS/outputs

  db:
    ports:
      - "5432:5432"
    volumes:
    - /home/ispq/qaboard/database_backups:/backups
      

  backend:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:backend"
    environment:
    - GITLAB_HOST=http://gitlab-srv
    - UWSGI_UID=arthurf
    - UWSGI_GID=uucp
    - QABOARD_DATA_SHARED_DIR=/home/ispq/qaboard/shared
    - QA_RUNNERS_LSF_BRIDGE='LC_ALL=en_US.utf8 LANG=en_US.utf8 ssh -q -tt -i /home/arthurf/.ssh/ispq.id_rsa ispq@ispq-vdi bsub_su {user} -I {bsub_command}'
    volumes:
    - ./services/backend/passwd:/etc/passwd
    - /opt/dockermounts/home:/home
    - /opt/dockermounts/raid:/raid
    - /opt/dockermounts/stage:/stage
    - /opt/dockermounts/home:/raid/users
    - /opt/dockermounts/stage/algo_data:/stage/algo_data
    - /data/asp_algorithms_data:/data/asp_algorithms_data
    - /stage/qa_data:/stage/qa_data
    - /sim:/sim
    - /stage/algo-datasets:/stage/algo-datasets
    - /net/f2/algo_archive:/stage/algo_archive
    # - /net/f2/algo_archive/DVS_SLAM_Database:/net/f2/algo_archive/DVS_SLAM_Database
    # - /net/f2/algo_archive/ToF_SW_Database:/net/f2/algo_archive/ToF_SW_Database
    # - /net/f2/algo_archive/PTAM_Results:/net/f2/algo_archive/PTAM_Results
    - /sim:/sim
    - /algo:/algo

  proxy:
    ports:
    - ${QABOARD_PORT_HTTPS:-443}:443
    - 80:5003
    # backward compat
    - "5000:5000"
    - "5002:5002"
    - "5003:8080"
    depends_on:
    - iiif-cde
    environment:
    - NGINX_USER=arthurf
    - QABOARD_PORT_HTTP=80
    volumes:
    - /home/arthurf/qaboard/services/nginx/ssl/dvs/dvs.key:/ssl/cert.key
    - /home/arthurf/qaboard/services/nginx/ssl/dvs/dvs.pem:/ssl/cert.pem    
    - ./services/nginx/passwd:/etc/passwd
    - /opt/dockermounts/home:/home
    - /opt/dockermounts/raid:/raid
    - /opt/dockermounts/stage:/stage
    - /opt/dockermounts/home:/raid/users
    - /opt/dockermounts/stage/algo_data:/stage/algo_data
    - /data/asp_algorithms_data:/data/asp_algorithms_data
    - /stage/qa_data:/stage/qa_data
    - /stage/algo-datasets:/stage/algo-datasets
    - /net/f2/algo_archive:/stage/algo_archive
    - /sim:/sim
    - /algo:/algo

  cantaloupe:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:cantaloupe"
    user: arthurf
    build:
      args:
        user: arthurf
        uid: 11611
        group: uucp
        gid: 10
    volumes:
      - /opt/dockermounts/stage/algo_data:/repository/stage/algo_data
      - /algo/CIS/outputs:/repository/algo/CIS/outputs
      - /algo/CIS_artifacts:/repository/algo/CIS_artifacts
    environment:
      CANTALOUPE_MEM_START: 4g
      CANTALOUPE_MEM_MAX: 8g
  
  frontend:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:frontend"

  website:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:website"


  metabase:
    image: metabase/metabase
    restart: always
    expose:
    - 3000
    volumes:
    - metabase.db:/metabase.db
    - metabase-data:/metabase-data
    depends_on:
    - db
    # https://www.metabase.com/docs/latest/operations-guide/environment-variables.html
    environment:
      MB_SITE_URL: https://qa/metabase
      MB_ADMIN_EMAIL: arthur.flam@samsung.com
      MB_ANON_TRACKING_ENABLED: "false"
      MB_ENABLE_EMBEDDING: "true"
      MB_ENABLE_PUBLIC_SHARING: "true"
      MB_QUERY_CACHING_MIN_TTL: 1
      # SMTP
      MB_EMAIL_FROM_ADDRESS: auto_delivery@samsung.com
      MB_EMAIL_SMTP_HOST: EX01.transchip.com
      # MB_EMAIL_SMTP_PASSWORD
      # MB_EMAIL_SMTP_USERNAME
      MB_LDAP_ENABLED: "true"
      MB_LDAP_USER_BASE: "OU=Sirc Users,DC=transchip,DC=com"
      MB_LDAP_BIND_DN: ldapquery@transchip.com
      MB_LDAP_PASSWORD: REDACTED_LDAP_PASSWORD
      MB_LDAP_HOST: transchip.com
      MB_LDAP_USER_FILTER: "(&(objectClass=user)(|(sAMAccountName={login})))"
      # We could save results in the main database but we need to dbcreate first...
      # MB_DB_TYPE: postgres
      # MB_DB_DBNAME: metabase
      # MB_DB_PORT: 5432
      # MB_DB_USER: qaboard
      # MB_DB_PASS: password
      # MB_DB_HOST: db

volumes:
  metabase-data: {}
  metabase.db: {}
