version: "3.5"
# dns: 127.0.0.53
# dns_search: transchip.com

services:
  iiif-cde:
    image: "gitlab-srv:4567/dvs/slamvizapp/iipsrv-cde"
    # command: 'tail -f /dev/null' # keeps the container up for debugging, but does nothing...
    restart: always
    expose:
    - "80"
    volumes:
    - /stage:/var/www/localhost/images/stage
    - /algo:/var/www/localhost/images/algo
    - /data:/var/www/localhost/images/data
    - /opt/dockermounts/home:/var/www/localhost/images/home
    - /sim:/var/www/localhost/images/sim:shared

  db:
    # postgres needs a file owned by postgres, and we cannot chown on our shared storage
    # the default entrypoint changes user from root to postgres and inits the database,
    # but only if the command starts with "postgres"... so we need to wrap it
    entrypoint: /init.sh
    volumes:
    - ./services/db/init.sh:/init.sh
    - ./services/db/postgres.conf:/postgres.host.conf
    - /home/ispq/qaboard_data_prod/database_backups:/backups
    ports:
      - ${QABOARD_EXPOSED_DB_PORT:-5432}:5432
  backend:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:backend"
    # deploy: # supported with swarm
    #   resources:
    #     limits:
    #       memory: 16000M
    environment:
    - GITLAB_HOST=http://gitlab-srv
    - UWSGI_UID=ispq
    - UWSGI_GID=uucp
    - QABOARD_DATA_SHARED_DIR=/home/ispq/qaboard/shared
    - QABOARD_DATA_GIT_DIR=/algo/ws/ispq/qaboard_prod_data_git
    - QA_RUNNERS_LSF_BRIDGE=ssh ispq@ispq-vdi 'bsub_su {user} -I {bsub_command}'
    - QABOARD_LOGIN_TYPE=LDAP
    - QABOARD_LDAP_USER_BASE=REDACTED_LDAP_BASE
    - QABOARD_LDAP_BIND_DN=cn=Ldap Query,ou=IT,ou=SIRC Users,REDACTED_LDAP_BASE
    - QABOARD_LDAP_PASSWORD=REDACTED_LDAP_PASSWORD
    - QABOARD_LDAP_HOST=REDACTED_LDAP_HOST
    - QABOARD_LDAP_USER_FILTER=(&(objectClass=user)(sAMAccountName={login}))
    - QABOARD_SAML_DIR=/qaboard/backend/backend/api/saml
    - QABOARD_SAML_ATTRIBUTE_EMAIL=http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
    - QABOARD_SAML_ATTRIBUTE_USER_NAME=http://schemas.sec.com/2018/05/identity/claims/LoginId
    - QABOARD_SAML_ATTRIBUTE_COMMON_NAME=http://schemas.sec.com/2018/05/identity/claims/Username
    - SENTRY_DSN=https://REDACTED_SENTRY_KEY@sentry.transchip.com/5

    volumes:
    - ./services/backend/passwd:/etc/passwd
    - /opt/dockermounts/home:/home
    - /opt/dockermounts/raid:/raid
    - /opt/dockermounts/stage:/stage
    - /opt/dockermounts/home:/raid/users
    - /opt/dockermounts/stage/algo_data:/stage/algo_data
    - /stage/qa_data:/stage/qa_data
    - /stage/algo-datasets:/stage/algo-datasets
    - /stage/algo_archive:/stage/algo_archive
    # - /net/f2/algo_archive/DVS_SLAM_Database:/net/f2/algo_archive/DVS_SLAM_Database
    # - /net/f2/algo_archive/ToF_SW_Database:/net/f2/algo_archive/ToF_SW_Database
    # - /net/f2/algo_archive/PTAM_Results:/net/f2/algo_archive/PTAM_Results
    - /sim:/sim:shared
    - /algo:/algo:shared
    - /data:/data:shared
    # we use a shared location to avoid using ~10G of local storage
    # but root can't write to it, so it's painful..
    # - /algo/ws/ispq/qaboard_data/_data:/var/qaboard

  proxy:
    ports:
    - ${QABOARD_PORT_HTTPS:-443}:443
    - ${QABOARD_PROXY_PORT_HTTP:-80}:5003
    # backward compat, from LSF accessing port 80 doesn't always work...
    - ${QABOARD_EXTRA_SIRC_PORT_1:-5000}:5000
    - ${QABOARD_EXTRA_SIRC_PORT_2:-5002}:5002
    depends_on:
    - iiif-cde
    environment:
    - NGINX_USER=ispq
    # - QABOARD_PORT_HTTP=80
    volumes:
    - /home/ispq/qaboard_prod/services/nginx/ssl/qa/qa.key:/ssl/cert.key
    - /home/ispq/qaboard_prod/services/nginx/ssl/qa/cert.cer:/ssl/cert.cer
    - /home/ispq/qaboard_prod/services/nginx/ssl/publish/publish.cer:/ssl/publish.cer
    - /home/ispq/qaboard_prod/services/nginx/ssl/publish/publish.pem:/ssl/publish.pem
    - /home/ispq/qaboard_prod/services/nginx/ssl/publish/publish.key:/ssl/publish.key
    - ./services/nginx/passwd:/etc/passwd
    - /opt/dockermounts/home:/home
    - /opt/dockermounts/raid:/raid
    - /opt/dockermounts/stage:/stage
    - /opt/dockermounts/home:/raid/users
    - /opt/dockermounts/stage/algo_data:/stage/algo_data
    - /stage/algo_archive:/stage/algo_archive
    - /stage/qa_data:/stage/qa_data
    - /stage/algo-datasets:/stage/algo-datasets
    - /algo:/algo:shared
    - /sim:/sim:shared
    - /data:/data:shared

  # cantaloupe:
  #   image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:cantaloupe"
  #   user: "1411:10" # FIXME: ==ispq, so remove after a 1st rebuild..
  #   # user: ispq
  #   build:
  #     args:
  #       user: ispq
  #       uid: 1411
  #       group: uucp
  #       gid: 10
  #   volumes:
  #     - /opt/dockermounts/stage/algo_data:/repository/stage/algo_data
  #     - /algo/CIS/outputs:/repository/algo/CIS/outputs
  #     - /algo/CIS_artifacts:/repository/algo/CIS_artifacts
  #     - /algo/ws/sircdevops/qaboard_data/cantaloupe:/var/cache/cantaloupe
  #     - /sim:/repository/sim:shared
  #     - /data:/data:shared
  #   environment:
  #     CANTALOUPE_MEM_START: 4g
  #     CANTALOUPE_MEM_MAX: 8g
  
  frontend:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:frontend"
    build:
      args:
        REACT_APP_SENTRY_DSN: https://REDACTED_SENTRY_FE_KEY@sentry.transchip.com/2

  website:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:website"


  metabase:
    image: metabase/metabase
    restart: always
    expose:
    - 3000
    volumes:
    - metabase.db:/metabase.db
    - metabase-data:/metabase-data
    depends_on:
    - db
    # https://www.metabase.com/docs/latest/operations-guide/environment-variables.html
    environment:
      MB_SITE_URL: https://qa/metabase
      MB_ADMIN_EMAIL: arthur.flam@samsung.com
      MB_ANON_TRACKING_ENABLED: "false"
      MB_ENABLE_EMBEDDING: "true"
      MB_ENABLE_PUBLIC_SHARING: "true"
      MB_QUERY_CACHING_MIN_TTL: 1
      # SMTP
      MB_EMAIL_FROM_ADDRESS: auto_delivery@samsung.com
      MB_EMAIL_SMTP_HOST: dag.sirc.co.il
      # MB_EMAIL_SMTP_PASSWORD
      # MB_EMAIL_SMTP_USERNAME
      MB_LDAP_ENABLED: "true"
      MB_LDAP_USER_BASE: "OU=Sirc Users,DC=transchip,DC=com"
      MB_LDAP_BIND_DN: ldapquery@transchip.com
      MB_LDAP_PASSWORD: REDACTED_LDAP_PASSWORD
      MB_LDAP_HOST: transchip.com
      MB_LDAP_USER_FILTER: "(&(objectClass=user)(|(sAMAccountName={login})))"
      # We could save results in the main database but we need to dbcreate first...
      # MB_DB_TYPE: postgres
      # MB_DB_DBNAME: metabase
      # MB_DB_PORT: 5432
      # MB_DB_USER: qaboard
      # MB_DB_PASS: password
      # MB_DB_HOST: db

volumes:
  metabase-data: {}
  metabase.db: {}
