[project]
name = "backend"
version = "1.0.1"
description = "Backend for QA-Board"
authors = [{ name = "Arthur Flam", email = "arthur.flam@samsung.com" }]
requires-python = ">=3.11"
license = "Apache-2.0"
dependencies = [
    "gitpython",
    "click",
    "flask",
    "flask_cors",
    "flask_login",
    "python-ldap",
    "sqlalchemy",
    "sqlalchemy_utils",
    "alembic",
    "psycopg2",
    "ujson",
    "pandas",
    "numpy",
    "scikit-image",
    "uwsgi",
    "uwsgitop",
    "scikit-optimize",
    "psutil",
    "certifi",
    "requests",
    "celery",
    "sentry-sdk[flask]",
    "python3-saml",
    "polyleven",
    "rich",
    "simplejson",
    "redis",
    "qaboard",
    # see https://github.com/xmlsec/python-xmlsec/issues/320
    "lxml",
    "xmlsec",
    "pillow",
    "pytz>=2026.1.post1",
]

[tool.setuptools.packages.find]
include = ["backend"] 

[tool.uv]
package = true
# see https://github.com/xmlsec/python-xmlsec/issues/320
# but not a good enough workaround..
no-binary-package = ["uwsgi", "lxml", "xmlsec", "psycopg2"]

# Unfortunately uv tries to resolve even extras we dont use
# Leading to ssh issues all over the place. So we can't just
# [project.optional-dependencies]
# sirc = [
#     "qaboard-site-sirc",
#     "cde @ git+ssh://git@gitlab-srv/cde/cde-python",
# ]
# dsk = [
#     "qaboard-site-dsk",
#     'cde @ git+ssh://git@github.sec.samsung.net/CDE/cde-python',
# ]

[tool.uv.sources]
qaboard = { path = "../" }
# qaboard-site-sirc = { path = "../deployments/sirc/cli" }
# qaboard-site-dsk = { path = "../deployments/dsk/cli" }

# [tool.uv.pip]
# no-binary = ["uwsgi", "lxml", "xmlsec"]

# uv sync --extra qaboard
# [project.optional-dependencies]
# qaboard = ["qaboard"]


[project.urls]
repository = "https://github.com/Samsung/qaboard"
homepage = "https://samsung.github.io/qaboard"


[project.scripts]
qaboard_clean = "backend.clean:clean"
qaboard_clean_untracked_hwalg_artifacts = "backend.clean:clean_untracked_hwalg_artifacts"
qaboard_clean_untracked_hwalg_outputs = "backend.clean:clean_untracked_hwalg_outputs"
qaboard_init_database = "backend.scripts.init_database:init_database"

[dependency-groups]
dev = ["pytest"]
