# .gitlab-ci.sample.yml
# reminder: `qatools` needs to be installed in your test runner's environment

performance:
  stage: performance
  script:
    - python main.py --recording=$my_recording run
    # will use the list of batch from the file defined in the configuration 
    - python main.py batch --group small


    - python main.py batch --recording-group small
    # tip: you can use the `--batch-label` flag to split your tests results

# FIXME: need to fix magic ENV SAMSUNG_$ variables
# FIXME: straightforward way to work/compile on LSF (`on_lsf`, `update_lsf`)
#        maybe via small CLI tools installed with `qatools`, that use the `CI_$` ENV variables
# FIXME: straightforward way to copy artifacts and parameters after build

