# !! Leave blank to use the JVM default temporary directory.
temp_pathname = /srv/cantaloupe

# !! Configures the HTTP server. (Standalone mode only.)
http.enabled = true
http.host = 0.0.0.0
http.port = 8182

# !! Configures the HTTPS server. (Standalone mode only.)
https.enabled = false
https.host = 0.0.0.0
https.port = 8183

# !! Available values are `JKS` and `PKCS12`. (Standalone mode only.)
https.key_store_type = JKS
https.key_store_password = myPassword
https.key_store_path = /path/to/keystore.jks
https.key_password = myPassword

# !! Constrains the size of the web server's thread pool. Leave blank to
# use the defaults.
http.min_threads =
http.max_threads =

# !! Maximum size of the HTTP(S) request queue. Set to 0 to use the default.
http.accept_queue_limit = 0

# Base URI to use for internal links, such as Link headers and JSON-LD
# @id values, in a reverse-proxy context. This should only be used when
# X-Forwarded-* headers cannot be used instead. (See the user manual.)
base_uri =

# Normally, slashes in a URI path component must be percent-encoded as
# "%2F". If your proxy is not able to pass these through without decoding,
# you can define an alternate character or character sequence to substitute
# for a slash. Supply the non-percent-encoded version here, and use the
# percent-encoded version in URLs.
slash_substitute =

# Maximum number of pixels to return in a response, to prevent overloading
# the server. Requests for more pixels than this will receive an error
# response. Set to 0 for no maximum.
# max_pixels = 400000000
max_pixels = 0

# Errors will also be logged to the error log (if enabled).
print_stack_trace_on_error_pages = true

# A meta-identifier is a superset of an identifier that includes other
# information like a page number and/or scale constraint. A meta-identifier
# transformer transforms a meta-identifier to and from a string in a URI
# path component.
# Available transformers include `StandardMetaIdentifierTransformer` and
# `DelegateMetaIdentifierTransformer`. See the user manual for more
# information about meta-identifiers and these options.
meta_identifier.transformer = StandardMetaIdentifierTransformer

# Character sequence that separates the components of a meta-identifier in
# the identifier portion of a URI.
meta_identifier.transformer.StandardMetaIdentifierTransformer.delimiter = ;

# If true, HTTP >= 400-level responses are logged at WARN and ERROR level.
# This may result in multiple log statements for the same error, but it may
# also help diagnose errors that have evaded logging.
log_error_responses = false

###########################################################################
# DELEGATE SCRIPT
###########################################################################

# !! Enables the delegate script: a Ruby script containing various delegate
# methods. (See the user manual.)
delegate_script.enabled = false

# !! This can be an absolute path, or a filename; if only a filename is
# specified, it will be searched for in the same folder as this file, and
# then the current working directory.
delegate_script.pathname = 


###########################################################################
# ENDPOINTS
###########################################################################

# Enables the IIIF Image API 1.x endpoint, at /iiif/1.
endpoint.iiif.1.enabled = false

# Enables the IIIF Image API 2.x endpoint, at /iiif/2.
endpoint.iiif.2.enabled = true

# Enables the IIIF Image API 3.x endpoint, at /iiif/3.
endpoint.iiif.3.enabled = true

# Minimum size that will be used in info.json `sizes` keys.
endpoint.iiif.min_size = 64

# Minimum size that will be used in info.json `tiles` keys. See the user
# manual to learn how these are calculated.
endpoint.iiif.min_tile_size = 512

# If true, requests for sizes other than those specified in an info.json
# response will be denied.
endpoint.iiif.restrict_to_sizes = false

# Enables the Control Panel, at /admin.
# endpoint.admin.enabled = false
# endpoint.admin.username = admin
# endpoint.admin.secret =
endpoint.admin.enabled = true
endpoint.admin.username = qaboard
endpoint.admin.secret = qaboard

# Enables the administrative HTTP API. (See the user manual.)
endpoint.api.enabled = false

# HTTP Basic credentials to access the HTTP API.
endpoint.api.username =
endpoint.api.secret =

# Enables the administrative HTTP API. (See the user manual.)
endpoint.api.enabled = true

# HTTP Basic credentials to access the HTTP API.
endpoint.api.username = ispq
endpoint.api.secret = ispq

# If true, sources and caches will be checked, resulting in a more robust
# but slower health check. Set this to false if these services already have
# their own health checks.
endpoint.health.dependency_check = false
###########################################################################
# RESOLVERS
###########################################################################

# Uses one source for all requests. Available values are `FilesystemSource`,
# `HttpSource`, `JdbcSource`, `S3Source`, and `AzureStorageSource`.
source.static = FilesystemSource

# If true, `source.static` will be overridden, and the `source()` delegate
# method will be used to select a source per-request.
source.delegate = false

#----------------------------------------
# FilesystemSource
#----------------------------------------

# How to look up files. Allowed values are `BasicLookupStrategy` and
# `ScriptLookupStrategy`. ScriptLookupStrategy uses the delegate script for
# dynamic lookups; see the user manual.
# FilesystemSource.lookup_strategy = ScriptLookupStrategy
FilesystemSource.lookup_strategy = BasicLookupStrategy
FilesystemSource.BasicLookupStrategy.path_prefix = /repository/

###########################################################################
# PROCESSORS
###########################################################################

#----------------------------------------
# Processor Selection
#----------------------------------------

# Image processors to use for various source formats. Available values are
# `Java2dProcessor`, `GraphicsMagickProcessor`, `ImageMagickProcessor`,
# `KakaduProcessor`, `OpenJpegProcessor`, `JaiProcessor`, `PdfBoxProcessor`,
# and `FfmpegProcessor`.

# These extension-specific definitions are optional.
processor.avi = FfmpegProcessor
processor.bmp =
processor.dcm =
processor.flv = FfmpegProcessor
processor.gif =
processor.jp2 = OpenJpegProcessor
processor.jpg =
processor.mov = FfmpegProcessor
processor.mp4 = FfmpegProcessor
processor.mpg = FfmpegProcessor
processor.pdf = PdfBoxProcessor
processor.png =
processor.tif = Java2dProcessor
processor.webm = FfmpegProcessor
processor.webp = ImageMagickProcessor
processor.ManualSelectionStrategy.xpm =


processor.imageio.xpm.reader =


# Fall back to this processor for any formats not assigned above.
processor.fallback = Java2dProcessor

#----------------------------------------
# PdfBoxProcessor
#----------------------------------------

# The following will enable disk to be used as well as memory during
# PDF loading in PdfBoxProcessor.  If `max_memory_bytes` is -1 it
# will use unlimited memory.
processor.pdf.scratch_file_enabled = false
processor.pdf.max_memory_bytes = -1

#----------------------------------------
# GrokProcessor
#----------------------------------------

# Optional absolute path of the directory containing grk_decompress.
# Overrides the PATH.
GrokProcessor.path_to_binaries =

#----------------------------------------
# Global Processor Configuration
#----------------------------------------

# Controls how content is fed to processors from stream-based sources.
# * `StreamStrategy` will try to stream a source image from a source when
#   possible, and use `processor.fallback_retrieval_strategy` otherwise.
# * `DownloadStrategy` will download it to a temporary file, and delete
#   it after the request is complete.
# * `CacheStrategy` will download it into the source cache using
#   FilesystemCache, which must also be configured. (This will perform a
#   lot better than DownloadStrategy if you can spare the disk space.)
processor.stream_retrieval_strategy = StreamStrategy

# Controls how an incompatible StreamSource + FileProcessor combination is
# dealt with.
# * `DownloadStrategy` and `CacheStrategy` work the same as above.
# * `AbortStrategy` causes the request to fail.
processor.fallback_retrieval_strategy = CacheStrategy

# Resolution of vector rasterization (of e.g. PDFs) at a scale of 1.
processor.dpi = 150

# Expands contrast to utilize available dynamic range. This forces the entire
# source image to be read into memory, so can be slow with large images.
processor.normalize = false

# Color of the background when an image is rotated or alpha-flattened, for
# output formats that don't support transparency.
# This may not be respected for indexed color derivative images.
processor.background_color = white

# Available values are `bell`, `bspline`, `bicubic`, `box`, `hermite`,
# `lanczos3`, `mitchell`, `triangle`. (JaiProcessor ignores these.)
processor.downscale_filter = bicubic
processor.upscale_filter = bicubic


# If true, images are downscaled in a linear color space, which is more
# accurate. This only works with mono-resolution (non-pyramidal) images. It
# also may impair performance.
processor.downscale_linear = false

# Intensity of an unsharp mask from 0 to 1.
processor.sharpen = 0

# Whether to reduce images with more than 8 bits per sample to 8 bits.
# This only applies to formats that support >8-bit samples, and not all
# processors respect this setting; see the user manual.
processor.limit_to_8_bits = true

# Progressive JPEGs are usually more compact.
processor.jpg.progressive = true

# JPEG output quality (1-100).
# processor.jpg.quality = 80
processor.jpg.quality = 100

# TIFF output compression type. Available values are `Deflate`, `JPEG`,
# `LZW`, and `RLE`. Leave blank for no compression.
processor.tif.compression = LZW

#----------------------------------------
# FfmpegProcessor
#----------------------------------------

# Optional absolute path of the directory containing the FFmpeg binaries.
# Overrides the PATH.
FfmpegProcessor.path_to_binaries =

#----------------------------------------
# KakaduProcessor
#----------------------------------------

# Optional absolute path of the directory containing the Kakadu binaries.
# Overrides the PATH.
KakaduProcessor.path_to_binaries =

#----------------------------------------
# OpenJpegProcessor
#----------------------------------------

# Optional absolute path of the directory containing the OpenJPEG binaries.
# Overrides the PATH.
OpenJpegProcessor.path_to_binaries =

###########################################################################
# CLIENT-SIDE CACHING
###########################################################################

# Whether to enable the response Cache-Control header.
cache.client.enabled = true

cache.client.max_age = 2592000
cache.client.shared_max_age =
cache.client.public = true
cache.client.private = false
cache.client.no_cache = false
cache.client.no_store = false
cache.client.must_revalidate = false
cache.client.proxy_revalidate = false
cache.client.no_transform = true

###########################################################################
# SERVER-SIDE CACHING
###########################################################################

# N.B.: The source cache may be used if the
# `processor.stream_retrieval_strategy` and/or
# `processor.fallback_retrieval_strategy` keys are set to `CacheStrategy`.

# FilesystemCache is the only available source cache.
cache.server.source = FilesystemCache

# Amount of time source cache content remains valid. Set to blank or 0
# for forever.
cache.server.source.ttl_seconds = 432000

# Enables the derivative (processed image) cache.
cache.server.derivative.enabled = true

# Available values are `FilesystemCache`, `JdbcCache`, `RedisCache`,
# `HeapCache`, `AmazonS3Cache`, and `AzureStorageCache`.
cache.server.derivative = FilesystemCache

# Amount of time derivative cache content remains valid. Set to blank or 0
# for forever.
cache.server.derivative.ttl_seconds = 432000

# Whether to use the Java heap as a "level 1" cache for image infos, either
# independently or in front of a "level 2" derivative cache (if enabled).
cache.server.info.enabled = true

# If true, when a resolver reports that the requested source image has gone
# missing, all cached information relating to it (if any) will be deleted.
# (This is effectively always false when cache.server.resolve_first is also
# false.)
cache.server.purge_missing = false

# If true, the source image will be confirmed to exist before a cached copy
# is returned. If false, the cached copy will be returned without checking.
# Resolving first is safer but slower.
cache.server.resolve_first = false

# !! Enables the cache worker, which periodically purges invalid cache
# items in the background.
cache.server.worker.enabled = true

# !! The cache worker will start its shifts this many seconds apart.
cache.server.worker.interval = 86400

#----------------------------------------
# FilesystemCache
#----------------------------------------

# If this directory does not exist, it will be created automatically.
FilesystemCache.pathname = /var/cache/cantaloupe

# Levels of folder hierarchy in which to store cached images. Deeper depth
# results in fewer files per directory. Set to 0 to disable subfolders.
# Purge the cache after changing this.
FilesystemCache.dir.depth = 3

# Number of characters in hierarchy directory names. Should be set to
# 16^n < (max number of directory entries your filesystem can deal with).
# Purge the cache after changing this.
FilesystemCache.dir.name_length = 2

###########################################################################
# OVERLAYS
###########################################################################

# Whether to enable overlays.
overlays.BasicStrategy.enabled = false

###########################################################################
# LOGGING
###########################################################################

#----------------------------------------
# Application Log
#----------------------------------------

# `trace`, `debug`, `info`, `warn`, `error`, `all`, or `off`
log.application.level = all

log.application.ConsoleAppender.logstash.enabled = false
log.application.FileAppender.logstash.enabled = false
log.application.RollingFileAppender.logstash.enabled = false

# info

log.application.ConsoleAppender.enabled = true

# N.B.: Don't enable FileAppender and RollingFileAppender simultaneously!
log.application.FileAppender.enabled = false
log.application.FileAppender.pathname = /var/logs/cantaloupe/application.log

log.application.RollingFileAppender.enabled = false
log.application.RollingFileAppender.pathname = /var/logs/cantaloupe/application.log
log.application.RollingFileAppender.policy = TimeBasedRollingPolicy
log.application.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /var/logs/cantaloupe/application-%d{yyyy-MM-dd}.log
log.application.RollingFileAppender.TimeBasedRollingPolicy.max_history = 30

# See the "SyslogAppender" section for a list of facilities:
# http://logback.qos.ch/manual/appenders.html
log.application.SyslogAppender.enabled = false
log.application.SyslogAppender.host =
log.application.SyslogAppender.port = 514
log.application.SyslogAppender.facility = LOCAL0

#----------------------------------------
# Error Log
#----------------------------------------

# Application log messages with a severity of WARN or greater can be copied
# into a dedicated error log, which may make them easier to spot.

# N.B.: Don't enable FileAppender and RollingFileAppender simultaneously!
log.error.FileAppender.enabled = false
log.error.FileAppender.pathname = /var/logs/cantaloupe/error.log

log.error.RollingFileAppender.enabled = true
log.error.RollingFileAppender.pathname = /var/logs/cantaloupe/error.log
log.error.RollingFileAppender.policy = TimeBasedRollingPolicy
log.error.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /var/logs/cantaloupe/error-%d{yyyy-MM-dd}.log
log.error.RollingFileAppender.TimeBasedRollingPolicy.max_history = 30
log.error.FileAppender.logstash.enabled = false
log.error.RollingFileAppender.logstash.enabled = false

#----------------------------------------
# Access Log
#----------------------------------------

log.access.ConsoleAppender.enabled = false

# N.B.: Don't enable FileAppender and RollingFileAppender simultaneously!
log.access.FileAppender.enabled = false
log.access.FileAppender.pathname = /var/logs/cantaloupe/access.log

# RollingFileAppender is an alternative to using something like
# FileAppender + logrotate.
log.access.RollingFileAppender.enabled = true
log.access.RollingFileAppender.pathname = /var/logs/cantaloupe/access.log
log.access.RollingFileAppender.policy = TimeBasedRollingPolicy
log.access.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /var/logs/cantaloupe/access-%d{yyyy-MM-dd}.log
log.access.RollingFileAppender.TimeBasedRollingPolicy.max_history = 30

# See the "SyslogAppender" section for a list of facilities:
# http://logback.qos.ch/manual/appenders.html
log.access.SyslogAppender.enabled = false
log.access.SyslogAppender.host =
log.access.SyslogAppender.port = 514
log.access.SyslogAppender.facility = LOCAL0

#----------------------------------------
# S3Source
#----------------------------------------

# !! AWS region. Only needed for AWS endpoints.
S3Source.region =

#----------------------------------------
# S3Cache
#----------------------------------------

# !! Endpoint URI. Only needed for non-AWS endpoints.
S3Cache.endpoint =

# !! AWS region. Only needed for AWS endpoints.
S3Cache.region =