{{- if .Values.redis.enabled }}
# A cache: no persistence, the backend works (slower) without it
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qaboard.fullname" . }}-redis
  labels: {{- include "qaboard.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "qaboard.selectorLabels" (list . "redis") | nindent 6 }}
  template:
    metadata:
      labels: {{- include "qaboard.selectorLabels" (list . "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["--save", "", "--appendonly", "no", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru", "--loglevel", "warning"]
          ports: [{name: redis, containerPort: 6379}]
          readinessProbe:
            tcpSocket: {port: redis}
          resources:
            requests: {cpu: 50m, memory: 128Mi}
            limits: {memory: 1500Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qaboard.fullname" . }}-redis
  labels: {{- include "qaboard.labels" . | nindent 4 }}
spec:
  selector: {{- include "qaboard.selectorLabels" (list . "redis") | nindent 4 }}
  ports: [{name: redis, port: 6379, targetPort: redis}]
{{- end }}
