########################
#                      #
#     Author: Itayk    #
#                      #
########################

# Define system configurations for fluentd
<system>
  # This doesnt work, default umask is set to 0022. Made a changes to the image to run as user 111778(sircdevops).
  file_permission 777 
</system>

# Define a source to get lgos from, the fluentd logging driver forwards container logs.
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# Match labels to outputs
<match qaboard.*>
  @type copy

  <store>
    @type elasticsearch
    scheme http
    host elk-srv.transchip.com
    port 9200
    logstash_format true
    logstash_prefix qaboard
    logstash_dateformat %m%Y
    include_tag_key true
    type_name access_log
    user elastic
    password changeme
    # template_name
    # pipeline 
  </store>
</match>


