# uwsgi configuration
# 
# Can 100% be ignored if you run the app via `flask run`

[uwsgi]
module = slamvizapp:app
master = true
processes = 5

# arthurf
# this lets us use SIRC NFS mounts, as they seem to squash_root
uid = arthurf
gid = uucp
# uid = 11611
# gid = 10

# protocol = uwsgi
# harakiri = 300

socket = /slamvizapp/deployment/slamvizapp.sock
# 777 for docker
chmod-socket = 777
# chmod-socket = 660
vacuum = true

die-on-term = true
# logto = /home/arthurf/dvs/slamvizapp/%n.log
