# uwsgi configuration
# 
# Can 100% be ignored if you run the app via `flask run`

[uwsgi]
module = slamvizapp:app
master = true
processes = 5


# protocol = uwsgi
# harakiri = 300

socket = deployment/slamvizapp.sock
chmod-socket = 660
vacuum = true

die-on-term = true
# logto = /home/arthurf/dvs/slamvizapp/%n.log
