server {
  # 80: http://dvd, when the dvd DNS name points to this host (qaboard.conf is the default server)
  listen 80;
  listen 5003;
  server_name dvd dvd.*;

  access_log /tmp/dvd-access.log;
  error_log /tmp/dvd-error.log;

  location / {
    proxy_pass http://qatools01:5044/;
  }
}
