# SIRC-specific nginx configuration
# Mounted by deployments/sirc/sirc.yml into /etc/nginx/conf.d/sirc.conf
upstream backend {
    server backend:3000;
}

server {
  server_name qa qatools01 proxy;
  listen 443 ssl default_server;
  listen 5000;
  listen 5002;
  listen 5003;
  listen 8080;

  ssl_certificate /ssl/cert.cer;
  ssl_certificate_key /ssl/cert.key;

  absolute_redirect off;

  location /docs {
    alias /docs/;
    try_files $uri $uri/index.html $uri.html /index.html;
  }

  location /docs/cis_utils/ {
    alias /algo/ws/ispq/docs/cis_utils/build/html;
    try_files $uri $uri/index.html $uri.html /index.html;
  }

  location / {
    root /builds;
    try_files $uri $uri/index.html $uri.html /index.html;
  }

  location ^~ /api {
    include uwsgi_params;
    uwsgi_pass backend;
    uwsgi_read_timeout 300;
    include cors;

    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host:$server_port;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Path /;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location ^~ /webhook {
    include uwsgi_params;
    uwsgi_pass backend;
    include cors;
  }

  # SIRC-specific file serving locations
  location ^~ /s/algo/ {
    alias /algo/;
    autoindex on;
    access_log off;
    include cors;
    gzip_static on;
    gunzip on;
  }

  location ^~ /s/stage/ {
    alias /stage/;
    autoindex on;
    access_log off;
    include cors;
    gzip_static on;
    gunzip on;
  }

  location ^~ /s/sim/ {
    alias /sim/;
    autoindex on;
    access_log off;
    include cors;
  }

  location ^~ /s/data/ {
    alias /data/;
    autoindex on;
    access_log off;
    include cors;
  }

  location ^~ /s/home/ {
    alias /home/;
    autoindex on;
    access_log off;
    include cors;
  }

  location ^~ /s/home/ispq {
    deny all;
  }

  # WebDAV
  # http://nginx.org/en/docs/http/ngx_http_dav_module.html
  location /davs/algo/ {
    alias /algo/;
    include /etc/nginx/webdav.conf;
  }

  # Metabase
  location /metabase/ {
    proxy_pass http://docker-prod-srv-1:3005/;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 600;
  }

  location ~ ^/metabase/(https?.*) {
    return 302 $1;
  }

  # pgAdmin
  location /pgadmin4/ {
    proxy_set_header X-Script-Name /pgadmin4;
    proxy_set_header Host $host;
    proxy_set_header X-Scheme $scheme;
    proxy_pass http://pgadmin:80/;
    proxy_redirect off;
  }
}
