[project]
name = "qaboard-site-dsk"
version = "1.0.0"
description = "QABoard site defaults for Samsung DSK"
requires-python = ">=3.7"
dependencies = [
    "cde @ git+ssh://git@github.sec.samsung.net/CDE/cde-python",
]

[project.entry-points."qaboard.site"]
dsk = "qaboard_site_dsk:defaults"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
