# if (-d $request_filename) { rewrite ^(.*[^/])$ $1/ break; }
# if ($request_method = MKCOL) { rewrite ^(.*[^/])$ $1/ break; }
autoindex               on;

client_body_temp_path /temp;
client_max_body_size 500M;

dav_methods             PUT DELETE MKCOL COPY MOVE;
dav_ext_methods         PROPFIND OPTIONS;
create_full_put_path    on;
dav_access              group:rw  all:r;
# enable creating directories without trailing slash
set $x $uri$request_method;
if ($x ~ [^/]MKCOL$) {
    rewrite ^(.*)$ $1/;
}


# $ sudo mkdir -p /etc/nginx/passwd
# $ sudo htpasswd -c /etc/nginx/passwd/webdav_pass S1rC
# auth_basic "Enter Password:";
# auth_basic_user_file "/etc/nginx/passwd/webdav_pass";
