# Metabase is hosted on docker-prod-srv-1
# TODO: Move this elsewhere!
version: "3.5"

volumes:
  metabase-db: {}
  metabase-data: {}

services:
  metabase-db:
    image: postgres:16
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
      PGDATA: /var/lib/postgresql/data
    volumes:
      - metabase-db:/var/lib/postgresql/data

  metabase:
    build:
      # Extends the usual "image: metabase/metabase" with proxy/ssl config
      dockerfile: services/metabase.Dockerfile
      context: .
    restart: always
    ports:
    - 3005:3000
    volumes:
    - metabase-data:/metabase-data
    - /raid/tools:/raid/tools
    - /home/ispq:/home/ispq
    depends_on:
    - metabase-db
    # https://www.metabase.com/docs/latest/operations-guide/environment-variables.html
    environment:
      # Database
      MB_DB_TYPE: postgres
      MB_DB_HOST: metabase-db
      MB_DB_PORT: 5432
      MB_DB_DBNAME: metabase
      MB_DB_USER: metabase
      MB_DB_PASS: metabase

      # General configuration
      MB_SITE_URL: https://qa/metabase
      MB_ADMIN_EMAIL: arthur.flam@samsung.com
      MB_ANON_TRACKING_ENABLED: "false"
      MB_ENABLE_EMBEDDING: "true"
      MB_ENABLE_PUBLIC_SHARING: "true"
      MB_QUERY_CACHING_MIN_TTL: 1
      JAVA_TIMEZONE: Asia/Jerusalem

      # Email
      MB_EMAIL_FROM_ADDRESS: auto_delivery@samsung.com
      MB_EMAIL_SMTP_HOST: dag.sirc.co.il
      # MB_EMAIL_SMTP_PASSWORD
      # MB_EMAIL_SMTP_USERNAME

      # LDAP
      MB_LDAP_ENABLED: "true"
      MB_LDAP_USER_BASE: "OU=Sirc Users,DC=transchip,DC=com"
      MB_LDAP_BIND_DN: ldapquery@transchip.com
      MB_LDAP_PASSWORD: REDACTED_LDAP_PASSWORD
      MB_LDAP_HOST: transchip.com
      MB_LDAP_USER_FILTER: "(&(objectClass=user)(|(sAMAccountName={login})))"

    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  backup:
    image: postgres:16
    # sircdevops
    user: 111778:10
    depends_on:
      - metabase-db
    volumes:
      - /raid/tools/devops/metabase/backups:/backups
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_HOST: metabase-db
      BACKUP_DAYS: 7  # Keep only the last 7 backups
    entrypoint: >
      /bin/sh -c "
      while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h metabase-db -U $$POSTGRES_USER -d $$POSTGRES_DB -F c -f /backups/metabase-$(date +%Y-%m-%d).dump && echo 'Backup OK!';
        find /backups -type f -name 'metabase-*.dump' -mtime +$$BACKUP_DAYS -delete;
        sleep 86400;
      done"
