# SIRC (Samsung Israel R&D Center) compose overlay
# Usage: docker compose -f docker-compose.yml -f production.yml -f deployments/sirc/sirc.yml -f deployments/sirc/prod.yml up

x-sirc-build-args: &sirc-build-args
  PROXY_URL: "http://webproxy.transchip.com:8080"
  CA_CERT_URL: "http://itweb/downloads/sirc-ca.crt"
  GIT_SERVER: "gitlab-srv"
  CDE_PACKAGE: "cde @ git+ssh://git@gitlab-srv/cde/cde-python"
  NO_PROXY: "gitlab-srv,gitlab-srv.transchip.com,localhost,aospt-dt,sentry,sentry.transchip.com"


services:
  fluentd:
    image: "gitlab-srv.transchip.com:4567/common-infrastructure/qaboard:fluentd${QABOARD_VERSION:+-$QABOARD_VERSION}"
    restart: always
    build:
      context: deployments/sirc/fluentd
      dockerfile: fluentd.Dockerfile
      args:
        <<: *sirc-build-args
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deployments/sirc/fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
    environment:
      - FLUENTD_CONF=fluentd.conf

  db:
    logging:
      driver: "fluentd"
      options:
        tag: qaboard.db
        fluentd-address: "0.0.0.0:24224"

  backend:
    logging:
      driver: "fluentd"
      options:
        tag: qaboard.backend
        fluentd-address: "0.0.0.0:24224"

  cron-backup-db:
    volumes:
    - /home/ispq/qaboard_data_prod/database_backups:/backups
    environment:
      AS_USER_NAME: ispq
      AS_USER_GROUP: uucp
      AS_USER_UID: "1411"
      AS_USER_GID: "10"
    logging:
      driver: "fluentd"
      options:
        tag: qaboard.cron-backup-db
        fluentd-address: "0.0.0.0:24224"
