import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // One sidebar per audience, see the navbar in docusaurus.config.ts

  // People who look at results in the web app
  userGuide: [
    "user-guide/overview",
    "user-guide/finding-results",
    "user-guide/commit-page",
    "user-guide/comparing-results",
    "user-guide/history-and-dashboards",
    "user-guide/running-from-the-webapp",
    "user-guide/sharing",
    "user-guide/tips-and-faq",
    "user-guide/whats-new",
  ],

  // Project leads who wrap their code with qa and set up qaboard.yaml
  docs: {
    "Getting Started": [
        "introduction",
        "installation",
        "project-init",
        "inputs",
        "running-your-code",
        "creating-and-viewing-outputs-files",
        "computing-quantitative-metrics",
        "specifying-configurations",
    ],
    "Guides": [
        "visualizations",
        "batches-running-on-multiple-inputs",
        "using-the-qa-cli",
        "references-and-milestones",
        "tuning-from-the-webapp",
        {
            type: 'category',
            label: 'Distributed Task Queues',
            items: [
                "local-multiprocessing",
                "celery-integration",
                "lsf-integration",
                "dask-integration",
                "jenkins-integration",
            ],
        },
        {
            type: 'category',
            label: 'Storage & Artifacts',
            items: [
              "storage/artifacts",
              "storage/where-is-the-data",
              "storage/deleting-old-data",
            ],
        },
        "triggering-third-party-tools",
        "ci-integration",
        "deep-learning",
        "debugging-runs-with-an-IDE",
        "metadata-integration-external-databases",
        "bit-accuracy",
        "faq",
        "apis",
        // "tuning-workflows",
        "dag-pipelines",
        // "history"
        "monorepo-subprojects",
        // "docker-integration",
        // "remote-platforms",
    ],
    // "Parameter Tuning": [
    // 	"Tuning Workflows",
    // 	"Enabling Tuning from QA-Board", // Save artifacts..
    // 	"Tuning runners", // setup LSF and != LSF///
    //   "Auto-Tuning"
    // ],
    //      ""
    //   "Admin Guides": [
    // 	  "starting-server",
    // 	  "server-maintenance"
    //   ]
    // "alternatives",
  },

  // Admins who run the QA-Board server
  admin: {
    "Server Admin": [
        "deploy",
        "backend-admin/deployment",
        "backend-admin/kubernetes",
        "backend-admin/troubleshooting",
        "backend-admin/host-upgrades",
        "backend-admin/user-management",
        "backend-admin/getting-SSL-certiticates-from-IT",
    ]
  }
};

module.exports = sidebars;
