#!/bin/sh
# Creates a backup
set -e

if [ "$1" = "" ]; then
    backup=$(date -I).dump
else
    backup=$1
fi

pg_dump -Fc > "/backups/$backup"

# TODO:
# - Remove backups older than X
# - upload the backup to e.g. S3
