#!/bin/sh
# Creates a backup
set -ex

if [ "$1" = "" ]; then
    backup=$(date -I).dump
else
    backup=$1
fi

if [ -z ${AS_USER_NAME+x} ]; then
  pg_dump -Fc > "/backups/$backup"
else
  # we should use gosu but it's nice to use the official image as-is
  addgroup -S $AS_USER_GROUP -g $AS_USER_GID group                            || true
  adduser --disabled-password $AS_USER_NAME -u $AS_USER_UID -G $AS_USER_GROUP || true
  su $AS_USER_NAME -c "pg_dump -Fc > '/backups/$backup'"
fi

# TODO:
# - Remove backups older than X
# - upload the backup to e.g. S3
