server {
  listen 5003;
  server_name publish;

  listen 443 ssl;
  ssl_certificate_key /ssl/publish.key;
  ssl_certificate /ssl/publish.pem;

  access_log /tmp/publish-access.log;
  error_log /tmp/publish-error.log;

  location / {
    proxy_pass http://qatools01:5045/;
  }
}
